version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests: [not_null, unique]

  - name: stg_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: customer_id
        tests: [not_null]
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ['fulfilled','returned','pending','cancelled']

  - name: fct_orders
    columns:
      - name: order_id
        tests: [not_null, unique]
      - name: outstanding_galleons
        tests: [not_null]