magic_shop:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: localhost
      port: 8123
      user: default
      password: ""
      secure: False
      verify: False
      schema: analytics
      threads: 4